### ISSUE TITLE
Unable to parse input tree

### ISSUE THREAD

**Issue by jianqiao-ms** [degdag/W.I.P_sagit_mainline#2]
following https://wiki.postmarketos.org/wiki/Xiaomi_Mi_6_(xiaomi-sagit)#Mainline kernel

Error happens when build:

Error: ../arch/arm64/boot/dts/qcom/msm8998-xiaomi-sagit.dtsi:516.1-17 syntax error
FATAL ERROR: Unable to parse input tree

**Comment by degdag** [comment]
Sorry it's now fixed and updated to 5.15
