### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by jianqiao-ms** [degdag/W.I.P_sagit_mainline#4]
Build error occur when following steps from https://wiki.postmarketos.org/wiki/Xiaomi_Mi_6_(xiaomi-sagit)

Error messege:

make[5]: *** No rule to make target '../../firmware//qcom/a508_zap.b00', needed by 'drivers/base/firmware_loader/builtin/qcom/a508_zap.b00.gen.o'.  Stop.

Environment: 
Ubuntu 21.10
gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2) 
pmbootstrap 1.40.0

Searching google for a while but nothing help.

**Comment by degdag** [comment]
> Build error occur when following steps from https://wiki.postmarketos.org/wiki/Xiaomi_Mi_6_(xiaomi-sagit)
> 
> Error messege:
> 
> make[5]: *** No rule to make target '../../firmware//qcom/a508_zap.b00', needed by 'drivers/base/firmware_loader/builtin/qcom/a508_zap.b00.gen.o'. Stop.
> 
> Environment: Ubuntu 21.10 gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2) pmbootstrap 1.40.0
> 
> Searching google for a while but nothing help.

You are using the wrong config 
try make -j8 sagit_defconfig
Use this config 

https://github.com/degdag/W.I.P_sagit_mainline/blob/d9ad5a19b76bbf05bc9e76efd58c09aeb4985b3a/arch/arm64/configs/sagit_defconfig#L1

**Comment by jianqiao-ms** [comment]
> > Build error occur when following steps from https://wiki.postmarketos.org/wiki/Xiaomi_Mi_6_(xiaomi-sagit)
> > Error messege:
> > make[5]: *** No rule to make target '../../firmware//qcom/a508_zap.b00', needed by 'drivers/base/firmware_loader/builtin/qcom/a508_zap.b00.gen.o'. Stop.
> > Environment: Ubuntu 21.10 gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2) pmbootstrap 1.40.0
> > Searching google for a while but nothing help.
> 
> You are using the wrong config try make -j8 sagit_defconfig Use this config
> 
> https://github.com/degdag/W.I.P_sagit_mainline/blob/d9ad5a19b76bbf05bc9e76efd58c09aeb4985b3a/arch/arm64/configs/sagit_defconfig#L1

It's WORDED!!!! THANKS A LOT! TOPEST RESPECT!
