### ISSUE TITLE
mi6 kernel not bootable

### ISSUE THREAD

**Issue by syabyr** [degdag/W.I.P_sagit_mainline#5]
# ubuntu env
20.04.4 LTS
Linux gen8 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
aarch64-linux-gnu-gcc -v
Using built-in specs.
COLLECT_GCC=aarch64-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc-cross/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu120.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --without-target-system-zlib --enable-libpth-m2 --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=aarch64-linux-gnu --program-prefix=aarch64-linux-gnu- --includedir=/usr/aarch64-linux-gnu/include
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

# How I compiled:
git clone https://github.com/degdag/W.I.P_sagit_mainline
cd W.I.P_sagit_mainline
git checkout Sagit/5.16.0-dev
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- sagit_defconfig
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j8
cat arch/arm64/boot/Image.gz arch/arm64/boot/dts/qcom/msm8998-xiaomi-sagit.dtb > ../Image.gz-dtb
cd ../
abootimg -u 5.11.14-xiaomi-msm8998.img -k ./Image.gz-dtb -c "bootsize=67108864"
mv 5.11.14-xiaomi-msm8998.img 5.16.0-xiaomi-msm8998.img

# boot failed:
fastboot boot 5.11.14-xiaomi-msm8998.img

after boot,the mi6 phone stayed in mi splash screen for a long time until I forced power-off.

**Comment by degdag** [comment]
You didn't pack any initrd (initramfs) so even if kernel works nothing will happen 
Anyway try to pack your boot img as what we do on postmarketos also you can use pmbootstrap to build and flash it

**Comment by degdag** [comment]
Also you need firmware files for GPU/WiFi /BL 
You can get it from my repo

**Comment by syabyr** [comment]
> You didn't pack any initrd (initramfs) so even if kernel works nothing will happen Anyway try to pack your boot img as what we do on postmarketos also you can use pmbootstrap to build and flash it

`abootimg -u 5.11.14-xiaomi-msm8998.img -k ./Image.gz-dtb -c "bootsize=67108864"`
means replace the kernel from 5.11.14-xiaomi-msm8998.img with the new one ./Image.gz-dtb
so i don`t need to pack initrd again.

I assume the problem might be "bootsize=67108864"?
and this argument comes from Boot image generation section of:
https://wiki.postmarketos.org/wiki/Xiaomi_Mi_6_(xiaomi-sagit)

**Comment by degdag** [comment]
> > You didn't pack any initrd (initramfs) so even if kernel works nothing will happen Anyway try to pack your boot img as what we do on postmarketos also you can use pmbootstrap to build and flash it
> 
> `abootimg -u 5.11.14-xiaomi-msm8998.img -k ./Image.gz-dtb -c "bootsize=67108864"` means replace the kernel from 5.11.14-xiaomi-msm8998.img with the new one ./Image.gz-dtb so i don`t need to pack initrd again.
> 
> I assume the problem might be "bootsize=67108864"? and this argument comes from Boot image generation section of: https://wiki.postmarketos.org/wiki/Xiaomi_Mi_6_(xiaomi-sagit)

Anyway I'm not the device maintainer anymore , didn't have the device right now and won't have it in future , 
There is someone that start continue working on it based on my previous works , you can check it from the link :

https://gitlab.com/msm8998-mainline/linux/-/merge_requests/1
